name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.269.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e048706e49c979dcc30ed4c94e948296397b399c2a4a0db76edd237ab883c6c6"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
