name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.272.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7820a6f67c299f7325fe207c128a02e5b18a6774ca04c4fdb6ac5813f229f8b"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
