name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.269.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e782d22c4135aa11243acd2ad88d1078dd867cfbccffee9585fc03f95ae5ca7"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
