name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.262.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce418093582d7f9312a948d902bddecda51ea5248efd10053008f24df86c4c43"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
