name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.272.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b251f26efb8ea8418bf6fe629f41111b0c9206c1ca6148db9d449bd591753607"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
