name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.265.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1431f5df16c4a6c613c5d8d42fc456bebb7a845263ef424dcb79fc7d749763e1"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
