name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.269.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55fa529f54e4a411266c924e579fff5cc4211ca169319c3a50a69cfb0b64b8e5"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
