name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.267.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70f9e7ce4a67ad3f4a5ef02a1f8c01ff8a9260ede0c630e4b54d32ce3df803ec"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
