name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.265.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0eeb275cde937abc5f82cdcbe8619c857a5e77f2f0c90ffb0aab95dc3eb6eec0"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
