name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.258.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c903375ab863e2e53189f21f24afe85b5c75081e773f186a5746a8becefd198"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
