name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.269.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d63e96e9a1db7871b9bca86dfc500d747190966985552ecd3159902cf93926b6"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
